name: docs

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build Typedoc
        run: nix develop --command bash -c "npm i && npm run typedoc"
      - name: Build Vitest UI (@vitest/ui)
        id: vitest
        continue-on-error: true
        run: nix develop --command bash -c "npm i && npm run ui"
      - name: Move Vitest UI Reposrt
        run: |
          mv ./html/ ./docs/html
      - name: Build Vitest Coverate (@vitest/coverage-v8)
        continue-on-error: true  
        run: nix develop --command bash -c "npm i && npm run coverage"
      - name: Move Vitest Coverage Reposrt
        continue-on-error: true
        run: |
          mv ./coverage/ ./docs/coverage
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
      - name: If Failed Test, exit 1
        if: steps.vitest.outcome == 'failure'
        run: exit 1
